permalink: pretty

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename/
  - scope:
      path: "index.html"
    values:
      permalink: /

exclude:
  - ".DS_Store"
